# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0002_driverprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driverprofile', to='pooler.Driver'),
        ),
    ]
