# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:22
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0003_auto_20171201_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='driver',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pooler.Driver'),
        ),
    ]
