# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0006_driverprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='driver',
        ),
        migrations.DeleteModel(
            name='DriverProfile',
        ),
    ]
