# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0009_auto_20171201_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=180)),
                ('last_name', models.CharField(max_length=180)),
                ('phone_number', models.PositiveIntegerField()),
            ],
        ),
    ]
