# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0010_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='passenger/profile-pic')),
                ('gender', models.CharField(blank=True, choices=[('F', 'female'), ('M', 'male'), ('Both', 'both'), ('None', 'non-specified')], default='None', max_length=30)),
                ('general_location', models.CharField(blank=True, max_length=255)),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pooler.Passenger')),
            ],
        ),
    ]
