# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0011_passengerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.TextField()),
                ('driver_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pooler.DriverProfile')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pooler.Passenger')),
            ],
        ),
    ]
