# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0013_passengerreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='car_image',
            field=models.ImageField(blank=True, default='car-image/car-default.png', upload_to='car-image/'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='driver/profile-pic/user-icon.png', upload_to='driver/profile-pic'),
        ),
    ]
