# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0016_travelplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelplan',
            options={'ordering': ['-travel_date']},
        ),
        migrations.AddField(
            model_name='travelplan',
            name='travel_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
