# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0017_auto_20171205_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='car_number_plate',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
