# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0018_auto_20171205_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pooler.PassengerProfile')),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pooler.TravelPlan')),
            ],
        ),
    ]
